title = "Dominika Gierszewska"
baseURL = "https://dominikagierszewska.com"
languageCode = "pl"
theme = "gohugo-theme-ananke"
js = "suncalc.js"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pl"
SectionPagesMenu = "main"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  favicon = ""
  description = "Artist"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/recall/recall1.jpg"
  recent_posts_number = 5
[languages]
  [languages.pl]
    weight=1
    languageName="PL"
  [languages.en]
    weight=2
    languageName="ENG"